# ---------------------------------------------------------
# Recommendation API Tests
# ---------------------------------------------------------
#
# These tests verify the Recommendation API from the HTTP
# layer all the way to the PostgreSQL test database.
# ---------------------------------------------------------

from uuid import uuid4

from app.models.recommendation import Recommendation
from app.tests.conftest import TestSessionLocal


# ---------------------------------------------------------
# HELPER — CREATE TEST RECOMMENDATION
# ---------------------------------------------------------

def create_test_recommendation(test_user):
    """
    Create a recommendation directly in the test database.

    Recommendations are generated by the intelligence system,
    so the API itself does not need a create endpoint.
    """

    db = TestSessionLocal()

    try:
        recommendation = Recommendation(
            user_id=test_user.id,
            recommendation_type="task_management",
            title="Reduce your pending task load",
            message="Review your pending tasks.",
            reason="You have several pending tasks.",
            source_signal="task_pressure",
            priority=0.9,
            status="generated",
        )

        db.add(recommendation)
        db.commit()
        db.refresh(recommendation)

        return recommendation.id

    finally:
        db.close()


# ---------------------------------------------------------
# GET USER RECOMMENDATIONS
# ---------------------------------------------------------

def test_get_user_recommendations(client, test_user):
    """
    The API should return all recommendations belonging
    to a user.
    """

    create_test_recommendation(test_user)

    response = client.get(
        "/api/v1/recommendations",
        params={"user_id": str(test_user.id)},
    )

    assert response.status_code == 200

    data = response.json()

    assert len(data) == 1
    assert data[0]["user_id"] == str(test_user.id)
    assert data[0]["recommendation_type"] == "task_management"
    assert data[0]["title"] == "Reduce your pending task load"
    assert data[0]["status"] == "generated"


# ---------------------------------------------------------
# GET SINGLE RECOMMENDATION
# ---------------------------------------------------------

def test_get_recommendation(client, test_user):
    """
    A recommendation should be retrievable using its ID.
    """

    recommendation_id = create_test_recommendation(test_user)

    response = client.get(
        f"/api/v1/recommendations/{recommendation_id}"
    )

    assert response.status_code == 200

    data = response.json()

    assert data["id"] == str(recommendation_id)
    assert data["user_id"] == str(test_user.id)
    assert data["title"] == "Reduce your pending task load"


# ---------------------------------------------------------
# GET NONEXISTENT RECOMMENDATION
# ---------------------------------------------------------

def test_get_nonexistent_recommendation(client):
    """
    Requesting a recommendation that doesn't exist should
    return 404.
    """

    recommendation_id = uuid4()

    response = client.get(
        f"/api/v1/recommendations/{recommendation_id}"
    )

    assert response.status_code == 404


# ---------------------------------------------------------
# UPDATE RECOMMENDATION STATUS
# ---------------------------------------------------------

def test_update_recommendation_status(client, test_user):
    """
    An existing recommendation should allow its lifecycle
    status to be updated.
    """

    recommendation_id = create_test_recommendation(test_user)

    response = client.patch(
        f"/api/v1/recommendations/{recommendation_id}",
        json={
            "status": "accepted",
        },
    )

    assert response.status_code == 200

    data = response.json()

    assert data["id"] == str(recommendation_id)
    assert data["status"] == "accepted"


# ---------------------------------------------------------
# DISMISS RECOMMENDATION
# ---------------------------------------------------------

def test_dismiss_recommendation(client, test_user):
    """
    A recommendation should be dismissible by changing
    its status to dismissed.
    """

    recommendation_id = create_test_recommendation(test_user)

    response = client.patch(
        f"/api/v1/recommendations/{recommendation_id}",
        json={
            "status": "dismissed",
        },
    )

    assert response.status_code == 200

    data = response.json()

    assert data["status"] == "dismissed"


# ---------------------------------------------------------
# UPDATE NONEXISTENT RECOMMENDATION
# ---------------------------------------------------------

def test_update_nonexistent_recommendation(client):
    """
    Updating a recommendation that doesn't exist should
    return 404.
    """

    recommendation_id = uuid4()

    response = client.patch(
        f"/api/v1/recommendations/{recommendation_id}",
        json={
            "status": "accepted",
        },
    )

    assert response.status_code == 404


# ---------------------------------------------------------
# GET USER WITH NO RECOMMENDATIONS
# ---------------------------------------------------------

def test_get_empty_user_recommendations(client, test_user):
    """
    A user with no recommendations should receive an
    empty list rather than an error.
    """

    response = client.get(
        "/api/v1/recommendations",
        params={"user_id": str(test_user.id)},
    )

    assert response.status_code == 200

    data = response.json()

    assert data == []