"""create activity events table

Revision ID: 61a35f049c5a
Revises: 93a2f79bdaa2
Create Date: 2026-09-26 23:40:32.760560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a35f049c5a'
down_revision: Union[str, Sequence[str], None] = '93a2f79bdaa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('task_created', 'task_updated', 'task_completed', 'task_cancelled', 'task_reopened', 'goal_created', 'goal_updated', 'goal_completed', 'goal_progress_updated', 'goal_cancelled', 'habit_created', 'habit_updated', 'habit_completed', 'habit_missed', 'habit_deactivated', 'project_created', 'project_updated', 'project_completed', 'project_archived', 'user_created', name='activityeventtype'), nullable=False),
    sa.Column('entity_type', sa.Enum('task', 'goal', 'habit', 'project', 'user', name='activityentitytype'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_events')
    # ### end Alembic commands ###
